/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Tomas
 */
public class Admin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioAdmin = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jBGMesas = new javax.swing.JButton();
        jBGMesero = new javax.swing.JButton();
        jBGProducto = new javax.swing.JButton();
        jBGPedidos = new javax.swing.JButton();
        jBGReservas = new javax.swing.JButton();

        javax.swing.GroupLayout EscritorioAdminLayout = new javax.swing.GroupLayout(EscritorioAdmin);
        EscritorioAdmin.setLayout(EscritorioAdminLayout);
        EscritorioAdminLayout.setHorizontalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        EscritorioAdminLayout.setVerticalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jBGMesas.setText("GESTION DE MESAS");
        jBGMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMesasActionPerformed(evt);
            }
        });

        jBGMesero.setText("GESTION DE MESERO");
        jBGMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMeseroActionPerformed(evt);
            }
        });

        jBGProducto.setText("GESTION DE PRODUCTOS");
        jBGProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGProductoActionPerformed(evt);
            }
        });

        jBGPedidos.setText("GESTION DE PEDIDOS");
        jBGPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGPedidosActionPerformed(evt);
            }
        });

        jBGReservas.setText("GESTION DE RESERVAS");
        jBGReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBGMesas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGReservas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBGMesas, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jBGMesero, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jBGProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jBGPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jBGReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EscritorioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EscritorioAdmin)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMesasActionPerformed
        AdminGMesas mesasFrame = new AdminGMesas (); // Suponiendo que tienes un JInternalFrame para gestionar mesas
        EscritorioAdmin.add(mesasFrame);
        mesasFrame.setVisible(true);
    }//GEN-LAST:event_jBGMesasActionPerformed

    private void jBGMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMeseroActionPerformed
        AdminGMeseros meserosFrame = new AdminGMeseros (); // Suponiendo que tienes un JInternalFrame para gestionar mesas
        EscritorioAdmin.add(meserosFrame);
        meserosFrame.setVisible(true);
    }//GEN-LAST:event_jBGMeseroActionPerformed

    private void jBGProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGProductoActionPerformed
        AdminGProductos productosFrame = new AdminGProductos (); // Suponiendo que tienes un JInternalFrame para gestionar mesas
        EscritorioAdmin.add(productosFrame);
        productosFrame.setVisible(true);
    }//GEN-LAST:event_jBGProductoActionPerformed

    private void jBGPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGPedidosActionPerformed
        AdminGPedidos pedidosFrame = new AdminGPedidos (); // Suponiendo que tienes un JInternalFrame para gestionar mesas
        EscritorioAdmin.add(pedidosFrame);
        pedidosFrame.setVisible(true);
    }//GEN-LAST:event_jBGPedidosActionPerformed

    private void jBGReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGReservasActionPerformed
        AdminGReserva reservasFrame = new AdminGReserva (); // Suponiendo que tienes un JInternalFrame para gestionar mesas
        EscritorioAdmin.add(reservasFrame);
        reservasFrame.setVisible(true);
    }//GEN-LAST:event_jBGReservasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioAdmin;
    private javax.swing.JButton jBGMesas;
    private javax.swing.JButton jBGMesero;
    private javax.swing.JButton jBGPedidos;
    private javax.swing.JButton jBGProducto;
    private javax.swing.JButton jBGReservas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
