/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;
import java.sql.Connection;
import Persistencia.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Roma
 */
public class Admin extends javax.swing.JInternalFrame {
    private Connection  connection;

    /**
     * Creates new form Admin
     */
    public Admin() {
    initComponents();
    this.connection = Conexion.getConexion();
    
    // Código para ajustar dinámicamente el tamaño y eliminar el espacio en blanco
    ajustarComponentes();

    jBGProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jBGProductoActionPerformed(evt);
        }
    });
    
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    fecha.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);

    // Quitar borde del JInternalFrame
    this.setBorder(null);
    ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
}

    // Método para ajustar componentes después de la inicialización
    private void ajustarComponentes() {
        // Ajusta el tamaño de EscritorioAdmin para que ocupe todo el espacio disponible
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ajustarEscritorio();
            }
        });
    }

    private void ajustarEscritorio() {
        // Ajustar tamaño de EscritorioAdmin según el tamaño del JInternalFrame
        barraUp.setSize(getWidth() - barraPanel.getWidth(), barraUp.getHeight());
        EscritorioAdmin.setSize(getWidth() - barraPanel.getWidth(), getHeight() - barraUp.getHeight());
        EscritorioAdmin.setLocation(barraPanel.getWidth(), barraUp.getHeight());
    }

           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioAdmin = new javax.swing.JDesktopPane();
        barraPanel = new javax.swing.JPanel();
        jBGMesas = new javax.swing.JButton();
        jBGMesero = new javax.swing.JButton();
        jBGProducto = new javax.swing.JButton();
        jBGPedidos = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        Resto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBGReservas1 = new javax.swing.JButton();
        barraUp = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));
        setClosable(true);
        setAlignmentX(0.0F);
        setAutoscrolls(true);

        EscritorioAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EscritorioAdminLayout = new javax.swing.GroupLayout(EscritorioAdmin);
        EscritorioAdmin.setLayout(EscritorioAdminLayout);
        EscritorioAdminLayout.setHorizontalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EscritorioAdminLayout.setVerticalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        barraPanel.setBackground(new java.awt.Color(0, 153, 153));

        jBGMesas.setText("MESAS");
        jBGMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMesasActionPerformed(evt);
            }
        });

        jBGMesero.setText("MESEROS");
        jBGMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMeseroActionPerformed(evt);
            }
        });

        jBGProducto.setText("PRODUCTOS");
        jBGProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGProductoActionPerformed(evt);
            }
        });

        jBGPedidos.setText("PEDIDOS");
        jBGPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGPedidosActionPerformed(evt);
            }
        });

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        Resto.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        Resto.setForeground(new java.awt.Color(0, 0, 0));
        Resto.setText("GESTION");

        jLabel1.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RESTO");

        jBGReservas1.setText("RESERVAS");
        jBGReservas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGReservas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraPanelLayout = new javax.swing.GroupLayout(barraPanel);
        barraPanel.setLayout(barraPanelLayout);
        barraPanelLayout.setHorizontalGroup(
            barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPanelLayout.createSequentialGroup()
                .addGroup(barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBGMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGReservas1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        barraPanelLayout.setVerticalGroup(
            barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jBGMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jBGMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jBGProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jBGPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBGReservas1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        barraUp.setBackground(new java.awt.Color(255, 153, 102));

        fecha.setBackground(new java.awt.Color(204, 153, 255));
        fecha.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout barraUpLayout = new javax.swing.GroupLayout(barraUp);
        barraUp.setLayout(barraUpLayout);
        barraUpLayout.setHorizontalGroup(
            barraUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraUpLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(758, Short.MAX_VALUE))
        );
        barraUpLayout.setVerticalGroup(
            barraUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EscritorioAdmin))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barraUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EscritorioAdmin)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMesasActionPerformed
        // Crear una instancia de GMesas
        GMesas mesasPanel = new GMesas();

        // Eliminar todos los componentes anteriores en el EscritorioAdmin
        EscritorioAdmin.removeAll();
        EscritorioAdmin.repaint();

        // Agregar el panel GMesas al EscritorioAdmin
        EscritorioAdmin.add(mesasPanel, BorderLayout.CENTER);

        // Configurar el tamaño y la visibilidad del panel
        mesasPanel.setVisible(true);
        mesasPanel.setSize(EscritorioAdmin.getWidth(), EscritorioAdmin.getHeight());
        mesasPanel.setLocation(0, 0);

        // Revalidar y repintar para asegurar que el nuevo panel se vea correctamente
        EscritorioAdmin.revalidate();
        EscritorioAdmin.repaint();
    }//GEN-LAST:event_jBGMesasActionPerformed

    private void jBGMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMeseroActionPerformed
        GMeseros meserosFrame = new GMeseros (); 
        EscritorioAdmin.add(meserosFrame,BorderLayout.CENTER);
        meserosFrame.setVisible(true);
        meserosFrame.setSize(780, 560);
        meserosFrame.setLocation(0, 0);
        EscritorioAdmin.removeAll();
        EscritorioAdmin.revalidate();
        EscritorioAdmin.repaint();

    }//GEN-LAST:event_jBGMeseroActionPerformed

    private void jBGProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGProductoActionPerformed
        // Crear una instancia del panel GProductos
        GProductos productosPanel = new GProductos();

        // Remover todos los componentes anteriores en el escritorio y limpiar
        EscritorioAdmin.removeAll();
        EscritorioAdmin.repaint();

        // Agregar el panel GProductos al EscritorioAdmin
        EscritorioAdmin.add(productosPanel, BorderLayout.CENTER);

        // Configurar tamaño y visibilidad del panel
        productosPanel.setVisible(true);
        productosPanel.setSize(EscritorioAdmin.getWidth(), EscritorioAdmin.getHeight());
        productosPanel.setLocation(0, 0);

        // Revalidar y repintar para asegurar que el nuevo panel se vea correctamente
        EscritorioAdmin.revalidate();
        EscritorioAdmin.repaint();

    }//GEN-LAST:event_jBGProductoActionPerformed

    private void jBGPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGPedidosActionPerformed
        GPedidos pedidosFrame = new GPedidos ();
        EscritorioAdmin.add(pedidosFrame,BorderLayout.CENTER);
        pedidosFrame.setVisible(true);
        pedidosFrame.setSize(780, 560);
        pedidosFrame.setLocation(0, 0);
        EscritorioAdmin.removeAll();
        EscritorioAdmin.revalidate();
        EscritorioAdmin.repaint();

    }//GEN-LAST:event_jBGPedidosActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
         this.setVisible(false); 
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGReservas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGReservas1ActionPerformed
        if (connection == null) {
            JOptionPane.showMessageDialog(null, "No se pudo establecer conexión con la base de datos.");
            return;
        }
        GReservas reservasFrame = new GReservas (connection); 
        // Remover todos los componentes anteriores en el escritorio y limpiar
        
        EscritorioAdmin.removeAll();
        EscritorioAdmin.repaint();

        // Agregar el panel GProductos al EscritorioAdmin
        EscritorioAdmin.add(reservasFrame, BorderLayout.CENTER);

        // Configurar tamaño y visibilidad del panel
        reservasFrame.setVisible(true);
        reservasFrame.setSize(EscritorioAdmin.getWidth(), EscritorioAdmin.getHeight());
        reservasFrame.setLocation(0, 0);

        // Revalidar y repintar para asegurar que el nuevo panel se vea correctamente
        EscritorioAdmin.revalidate();
        EscritorioAdmin.repaint();
    }//GEN-LAST:event_jBGReservas1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioAdmin;
    private javax.swing.JLabel Resto;
    private javax.swing.JPanel barraPanel;
    private javax.swing.JPanel barraUp;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jBGMesas;
    private javax.swing.JButton jBGMesero;
    private javax.swing.JButton jBGPedidos;
    private javax.swing.JButton jBGProducto;
    private javax.swing.JButton jBGReservas1;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
