/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JPanel;
import java.sql.Connection;
import Persistencia.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Roma
 */
public class Admin extends javax.swing.JInternalFrame {
    private Connection  connection;

    /**
     * Creates new form Admin
     */
    public Admin() {
    initComponents();
    this.connection = Conexion.getConexion();
    ajustarComponentes();
    mostrarFechaActual();
    configurarFrame();
    
    }
    private void configurarFrame() {
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    private void mostrarFechaActual() {
        LocalDate now = LocalDate.now();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        fecha.setText(String.format("Hoy es %d de %s de %d", now.getDayOfMonth(), meses[now.getMonthValue() - 1], now.getYear()));
    }

    private void ajustarComponentes() {
    EscritorioAdmin.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            if (EscritorioAdmin.getComponentCount() > 0) {
                JPanel panel = (JPanel) EscritorioAdmin.getComponent(0);
                panel.setBounds(0, 0, EscritorioAdmin.getWidth(), EscritorioAdmin.getHeight());
                EscritorioAdmin.revalidate();
                EscritorioAdmin.repaint();
            }
        }
    });
}



    private void ajustarEscritorio() {
        int anchoDisponible = getWidth() - barraPanel.getWidth();
        int altoDisponible = getHeight() - barraUp.getHeight();
        barraUp.setSize(anchoDisponible, barraUp.getHeight());
        EscritorioAdmin.setSize(anchoDisponible, altoDisponible);
        EscritorioAdmin.setLocation(barraPanel.getWidth(), barraUp.getHeight());
    }

   private void cargarPanel(JPanel panel) {
    // Elimina todos los componentes existentes en EscritorioAdmin
    EscritorioAdmin.removeAll();
    
    // Configura el layout de EscritorioAdmin como BorderLayout para asegurarte de que el panel se ajuste correctamente
    EscritorioAdmin.setLayout(new BorderLayout());
    
    // Añade el nuevo panel al centro de EscritorioAdmin para que ocupe todo el espacio disponible
    EscritorioAdmin.add(panel, BorderLayout.CENTER);

    // Refresca EscritorioAdmin para que se vean los cambios
    EscritorioAdmin.revalidate();
    EscritorioAdmin.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscritorioAdmin = new javax.swing.JDesktopPane();
        barraPanel = new javax.swing.JPanel();
        jBGMesas = new javax.swing.JButton();
        jBGMesero = new javax.swing.JButton();
        jBGProducto = new javax.swing.JButton();
        jBGanancias = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        Resto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBGReservas = new javax.swing.JButton();
        jBGPedidos = new javax.swing.JButton();
        barraUp = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));
        setClosable(true);
        setAlignmentX(0.0F);
        setAutoscrolls(true);

        EscritorioAdmin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EscritorioAdminLayout = new javax.swing.GroupLayout(EscritorioAdmin);
        EscritorioAdmin.setLayout(EscritorioAdminLayout);
        EscritorioAdminLayout.setHorizontalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EscritorioAdminLayout.setVerticalGroup(
            EscritorioAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        barraPanel.setBackground(new java.awt.Color(0, 153, 153));

        jBGMesas.setText("MESAS");
        jBGMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMesasActionPerformed(evt);
            }
        });

        jBGMesero.setText("MESEROS");
        jBGMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGMeseroActionPerformed(evt);
            }
        });

        jBGProducto.setText("PRODUCTOS");
        jBGProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGProductoActionPerformed(evt);
            }
        });

        jBGanancias.setText("GANANCIAS");
        jBGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGananciasActionPerformed(evt);
            }
        });

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        Resto.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        Resto.setForeground(new java.awt.Color(0, 0, 0));
        Resto.setText("GESTION");

        jLabel1.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RESTO");

        jBGReservas.setText("RESERVAS");
        jBGReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGReservasActionPerformed(evt);
            }
        });

        jBGPedidos.setText("PEDIDOS");
        jBGPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraPanelLayout = new javax.swing.GroupLayout(barraPanel);
        barraPanel.setLayout(barraPanelLayout);
        barraPanelLayout.setHorizontalGroup(
            barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPanelLayout.createSequentialGroup()
                .addGroup(barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(barraPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Resto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        barraPanelLayout.setVerticalGroup(
            barraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jBGMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBGReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barraUp.setBackground(new java.awt.Color(255, 153, 102));

        fecha.setBackground(new java.awt.Color(204, 153, 255));
        fecha.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout barraUpLayout = new javax.swing.GroupLayout(barraUp);
        barraUp.setLayout(barraUpLayout);
        barraUpLayout.setHorizontalGroup(
            barraUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraUpLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
        );
        barraUpLayout.setVerticalGroup(
            barraUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EscritorioAdmin)
                    .addComponent(barraUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barraUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EscritorioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMesasActionPerformed
        cargarPanel(new GMesas());
    }//GEN-LAST:event_jBGMesasActionPerformed

    private void jBGMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGMeseroActionPerformed
        cargarPanel(new GMeseros());
    }//GEN-LAST:event_jBGMeseroActionPerformed

    private void jBGProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGProductoActionPerformed
        cargarPanel(new GProductos());
    }//GEN-LAST:event_jBGProductoActionPerformed

    private void jBGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGananciasActionPerformed
        cargarPanel(new GGanancias(connection));
    }//GEN-LAST:event_jBGananciasActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose(); 
        Menu menu = new Menu(); 
        menu.setVisible(true); 
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBGReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGReservasActionPerformed
        if (connection == null) {
            JOptionPane.showMessageDialog(null, "No se pudo establecer conexión con la base de datos.");
            return;
        }
         cargarPanel(new GReservas(connection));
    }//GEN-LAST:event_jBGReservasActionPerformed

    private void jBGPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGPedidosActionPerformed
        if (connection == null) {
            JOptionPane.showMessageDialog(null, "No se pudo establecer conexión con la base de datos.");
            return;
        }cargarPanel(new GPedidos(connection ));
    }//GEN-LAST:event_jBGPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioAdmin;
    private javax.swing.JLabel Resto;
    private javax.swing.JPanel barraPanel;
    private javax.swing.JPanel barraUp;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jBGMesas;
    private javax.swing.JButton jBGMesero;
    private javax.swing.JButton jBGPedidos;
    private javax.swing.JButton jBGProducto;
    private javax.swing.JButton jBGReservas;
    private javax.swing.JButton jBGanancias;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
